### PR TITLE
fix: Dashboard dropdown cleanup

### LINKED ISSUE #196: Put dropdown description in variable for control panel
Right now, the spotlight page repeats the same description text in multiple places. It should be put in a variable so it doesn't need to be updated in two places.

Add description to dropDown value and pass that to ControlPanel so that ControlPanel handles everything for the dropdowns and conditional display doesn't need to be in the dashboard.

### PR DESCRIPTION
**Pull request by anna-murphy**
Removed duplicate dropdown definition.

 - Fixes #196

@s-bessey I think this is the fix you were talking about? If you wouldn't mind giving this a quick look to make sure, that would be wonderful 😄

### CODE REVIEW

File: src/views/spotlights/housing/dashboard.vue [hunk 1]
```diff
@@ -319,30 +319,10 @@ const updateCaseControls = (newControls) => {
...
-});
-
-useQueryParam({
-  param: "age",
-  ref: controls,
-  refField: "age",
-  valid: (p) => dropDowns.age.values.some((v) => p === v.value),
-  valToParam: (v) => v.value,
-  paramToVal: (p) => dropDowns.age.values.find((v) => p === v.value),
+  age: caseDropDown.age.values[0],
```
Comment (s-bessey) [inline src/views/spotlights/housing/dashboard.vue:325]: Hmm, we do want queryparams for both dropdowns

File: src/views/spotlights/housing/dashboard.vue [hunk 2]
```diff
@@ -319,30 +319,10 @@ const updateCaseControls = (newControls) => {
...
-  },
-};
-
 const hospFocus = { name: "Hospitalizations", value: "hospitalizations" };
 
 const controls = ref({
-  age: dropDowns.age.values[0],
-});
-
-useQueryParam({
```
Comment (s-bessey) [inline src/views/spotlights/housing/dashboard.vue:339]: Hmm, we do want queryparams for both dropdowns

Comment (anna-murphy) [reply src/views/spotlights/housing/dashboard.vue:339]: Oh! If that's the case, then I think we should change the key, because I'm pretty sure it's only giving one option param as is 😅

Comment (s-bessey) [reply src/views/spotlights/housing/dashboard.vue:339]: Right now, we have "age" and "cases" as keywords. "Age" is... not ideal there, though. This whole page certainly needs some cleanup! 
image

**Review by s-bessey — APPROVED** [review]

File: src/views/spotlights/housing/dashboard.vue (hunk 2 above)
Comment (anna-murphy) [reply src/views/spotlights/housing/dashboard.vue:339]: fixed 🚀

**Review by eldu — APPROVED** [review]

**Comment by anna-murphy** [comment]
The query parameters are inverted presently (so case maps to the hosp parameter and vice versa). This probably shouldn't be merged until we fix this.

**Review by eldu — CHANGES_REQUESTED** [review]
did the query params ever get fixed for this?

**Review by eldu — APPROVED** [review]
I took a look and it looks fine to me? I guess i'm not understanding the blocker at the moment @s-bessey can you take a look at this PR again?

**Comment by anna-murphy** [comment]
@eldu the problem was that, if I remember correctly, it was supposed to be reversed, such that the query param that corresponded with each dropdown value displays the wrong element (where the query param says "adjusted", it should say "specific").

This isn't the most important, it's just like not perfect. I'd be okay to merge it but I wasn't sure because it wasn't quite what it was supposed to be.

**Review by eldu — CHANGES_REQUESTED** [review]
the bottom dropdown is affecting the top dropdown for some reason

File: src/views/spotlights/housing/dashboard.vue [hunk 3]
```diff
@@ -319,30 +317,19 @@ const updateCaseControls = (newControls) => {
...
 useQueryParam({
-  param: "age",
+  param: "hospage",
   ref: controls,
   refField: "age",
-  valid: (p) => dropDowns.age.values.some((v) => p === v.value),
+  valid: (p) => caseDropDown.age.values.some((v) => p === v.value),
   valToParam: (v) => v.value,
-  paramToVal: (p) => dropDowns.age.values.find((v) => p === v.value),
+  paramToVal: (p) => caseDropDown.age.values.find((v) => p === v.value),
```
Comment (s-bessey) [inline src/views/spotlights/housing/dashboard.vue:332]: caseDropDown on hospitalization again

File: src/views/spotlights/housing/dashboard.vue [hunk 4]
```diff
@@ -66,16 +66,12 @@
...
-        distributions - meaning one group may have more old people, or one group
-        may have more young people. Age adjusting makes it so we can compare
-        between groups that have different age distributions.
-      </div>
-      <div v-else-if="caseControls.age.value === 'specific'">
-        Rates tell us how many people have tested positive for COVID-19 compared
-        to a larger group taking into account the population size of that group.
+      <div>
+        {{
+          controls.age.value === "adjusted"
```
Comment (s-bessey) [inline src/views/spotlights/housing/dashboard.vue:71]: why did we get rid of the distinction between caseControls and separate controls for hospitalizations?

**Review by s-bessey — CHANGES_REQUESTED** [review]
There are some issues with the distinctions between the two dropdowns leading to the drop-down descriptor text changing with the wrong dropdown being changed.

**Review by eldu — APPROVED** [review]
fixed in code buddies !

**Review by s-bessey — APPROVED** [review]
:shipit:
